---
title: "HW_statprog"
author: "Zarva_I"
date: "2024-12-29"
output: html_document
---

```{r}
library(dplyr)
library(lubridate)
library(openxlsx)
```

```{r}

adsl <- read.xlsx("ADaM coding/ADaM-like/ADSL.xlsx")
mh <- read.xlsx("data/raw//SDTM/MH_MEDICALHISTORY.xlsx")

mh <- mh %>%
  filter(!is.na(MHTERM) & MHTERM != "") %>%  # Исключить пустые строки
  mutate(
    MHSTDTC = ifelse(nchar(MHSTDTC) == 7, paste0(MHSTDTC, "-01"),
              ifelse(nchar(MHSTDTC) == 4, paste0(MHSTDTC, "-01-01"),
                     MHSTDTC)),
    MHENDTC = ifelse(nchar(MHENDTC) == 7, paste0(MHENDTC, "-01"),
              ifelse(nchar(MHENDTC) == 4, paste0(MHENDTC, "-01-01"),
                     MHENDTC)),
    ASTDT = ifelse(!is.na(MHSTDTC), format(as.Date(MHSTDTC, format = "%Y-%m-%d"), "%d.%m.%Y"), ""),
    AENDT = ifelse(!is.na(MHENDTC), format(as.Date(MHENDTC, format = "%Y-%m-%d"), "%d.%m.%Y"), "")
  )

adm_h <- mh %>%
  left_join(adsl, by = "SUBJID") %>%  
  select(
    SUBJID, USUBJID, STUDYID.x, STUDYID.y, SITEID, ARM, TRTP, TRTPN,
    MHTERM, MHDECOD, MHSTDTC, MHENDTC, ASTDT, AENDT
  )
adm_h <- adm_h %>%
  rename(STUDYID = STUDYID.x) %>%  
  select(-STUDYID.y)
str(adm_h)
write.xlsx(adm_h, "ADaM coding/ADaM-like/ADMH.xlsx")
```

