---
title: "HW_statprog"
author: "Zarva_I"
date: "2024-12-29"
output: html_document
---

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)
```

```{r}
pop_list <- read.xlsx("SDTM/Population_list.xlsx")
dem_ds <- read.xlsx("SDTM/DM_DEMOGRAPHICS.xlsx")
disp_ds <- read.xlsx("SDTM/DS_DISPOSITION.xlsx")
supp_disp <- read.xlsx("SDTM/SUPPDS_DISPOSITION.xlsx")
su_ds <- read.xlsx("SDTM/SU_SUBSTANCEUSE.xlsx")
vs_ds <- read.xlsx("SDTM/VS_VITALSIGNS.xlsx")
ex_ds <- read.xlsx("SDTM/EX_EXPOSURE.xlsx")

```

```{r dm}
sl_ds <- 
  dem_ds %>% 
  select(STUDYID, SUBJID, SITEID, 
         AGE, AGEU, 
         SEX, RACE, 
         ARM) %>% 
  mutate(SITEID = as.character(SITEID), 
         USUBJID = paste(STUDYID, SUBJID, sep = '-'),
         AGE = as.numeric(AGE),
         TRTP = ARM,
         TRTPN = c(1,2)[match(TRTP, c("XXXX0", "XXXX1"))])
```

```{r ds_dates}
dates_ds <- 
  disp_ds %>% 
  select(SUBJID, DSSEQ, DSSTDTC) %>% 
  mutate(DSSTDTC = format(as.Date(DSSTDTC, 
                                  format = "%Y-%m-%d"), 
                          "%d.%m.%Y")) %>% 
  pivot_wider(names_from = DSSEQ, 
              values_from = DSSTDTC) %>%
  select(SUBJID, RFICDT = '1', RANDDT = '2', EOSDT = '3')
```

```{r trt_dates}
trt_dates <- ex_ds %>% 
  group_by(SUBJID) %>% 
  mutate(N = length(EXSEQ[EXOCCUR == 'Yes' & 
                            !is.na(EXOCCUR)]),
         L = last(EXSEQ[EXOCCUR == 'Yes' & 
                          !is.na(EXOCCUR)])) %>% 
  ungroup() %>% 
  mutate(TYPE = ifelse(EXSEQ == 1, 'TRTSDT',
                       ifelse(EXSEQ == L, 'TRTEDT', '')),
         EXSTDTC = format(as.Date(EXSTDTC, 
                                  format = "%Y-%m-%d"), 
                          "%d.%m.%Y")) %>% 
  filter(TYPE != '') %>% 
  select(SUBJID, EXSTDTC, TYPE) %>% 
  spread(TYPE, EXSTDTC)

trt_dates <- left_join(trt_dates, dates_ds) 

trt_dates <- trt_dates %>% 
  mutate(TRTDURD = as.numeric(as.Date(TRTEDT, 
                           format = "%d.%m.%Y") - as.Date(TRTSDT, 
                                                          format = "%d.%m.%Y")))


```

```{r vs}
vs_res <- 
  vs_ds %>% 
  filter(VISIT == 'Visit 0', 
         VSSEQ %in% c('1','2','3')) %>% 
  select(SUBJID, VSTEST, VSORRES) %>% 
  pivot_wider(names_from = VSTEST, 
              values_from = VSORRES) %>%
  rename(WEIGHT = Weight,
         HEIGHT = Height)

vs_u <- 
  vs_ds %>% 
  filter(VISIT == 'Visit 0', 
         VSSEQ %in% c('1','2','3')) %>% 
  select(SUBJID,VSTEST, VSORRESU) %>% 
  pivot_wider(names_from = VSTEST, 
              values_from = VSORRESU) %>%
  rename(WEIGHTU = Weight,
         HEIGHTU = Height,
         BMIU = BMI)

vs_ds <- left_join(vs_res, vs_u)
```

```{r su}
su_ds <- 
  su_ds %>% 
  select(SUBJID, SUCAT, SUDOSTXT) %>% 
  pivot_wider(names_from = SUCAT, values_from = SUDOSTXT) %>% 
  rename(SMOKSTAT = 'Tobacco Use', ALCSTAT = 'Alcohol Use')
```

```{r do_dc_reas}
doreas <- 
  supp_disp %>% 
  filter(DSSEQ == 2) %>% 
  mutate(DOREAS = DSREAS) %>% 
  select(SUBJID, DOREAS, DSSTATUS, RANDID = DSNUM)

dcsreas <- 
  supp_disp %>% 
  filter(DSSEQ == 3) %>% 
  mutate(DCSREAS = DSREAS) %>% 
  select(SUBJID, DCSREAS)

do_dc_ds <- left_join(doreas, dcsreas)

```

```{r flags}
compl_fl <- supp_disp %>% 
  filter(DSSEQ == "3") %>%
  mutate(COMPLFL = ifelse(
    (grepl('Subject discontinued the study', DSSTATUS)), 
    'N', 'Y')) %>% 
  select(SUBJID, COMPLFL)

colnames(pop_list) <- c('STUDYID', 'SUBJID', 
                        'STATUS', 'RANDN', 
                         'PP', 'PPXL', 
                         'FAS',	'FASXL', 
                         'SAF', 'SAFXL')
pop_list <- pop_list %>%
  mutate_at(vars(PP, FAS, SAF), str_to_title)

pop_list <- pop_list %>% 
  mutate(PPROTFL = if_else(PP == 'Yes', 'Y', 'N'),
         FASFL = if_else(FAS == 'Yes', 'Y', 'N'),
         SAFFL = if_else(SAF == 'Yes', 'Y', 'N')
         ) %>% 
  select(SUBJID, 
         PPROTFL, PPXL,
         FASFL, FASXL,
         SAFFL, SAFXL)

```

```{r joins}
ADSL <- left_join(sl_ds, pop_list)
ADSL <- left_join(ADSL, do_dc_ds)
ADSL <- left_join(ADSL, trt_dates)
ADSL <- left_join(ADSL, su_ds)
ADSL <- left_join(ADSL, compl_fl)
ADSL <- left_join(ADSL, vs_ds)
```

```{r rand}
ADSL <- ADSL %>% 
  mutate(RANDFL = ifelse(is.na(RANDDT), 'N', 'Y'))
```

```{r adsl}
ADSL <- ADSL %>%
  select(STUDYID, SUBJID, USUBJID, SITEID,
         ARM, TRTP, TRTPN,
         RFICDT, RANDDT, TRTSDT, TRTEDT, TRTDURD, EOSDT,
         AGE, AGEU,
         SEX, RACE,
         WEIGHT, WEIGHTU,
         HEIGHT, HEIGHTU,
         BMI, BMIU,
         SMOKSTAT, ALCSTAT, 
         DOREAS, DCSREAS,
         FASFL, FASXL,
         PPROTFL, PPXL,
         SAFFL, SAFXL,
         RANDFL, COMPLFL)

ADSL <- ADSL %>%
  mutate_at(vars(TRTPN, TRTDURD,
                 AGE, WEIGHT, HEIGHT,
                 BMI), as.numeric) %>%
  mutate(WEIGHT = round(WEIGHT, digits = 1),
         BMI = round(BMI, digits = 2),
         HEIGHT = ceiling(HEIGHT))
  
```

```{r}
write.xlsx(ADSL, "./ADaM-like/ADSL.xlsx")
```

```{r}
colnames(ADSL)
```
# ADMH 

```{r}
# Согласно спецификации STUDYID, USUBJID, TRTP, TRTPN, MHSEQ, MHCAT, MHTERM, MHDECOD, MHBODSYS, MHSTDTC, ASTDT, ASTDTF, MHENDTC, AENDT, AENDTF, MHENRTPT, MHENRF
```

# Загрузка ADSL MH

```{r}
ADSL_1 <- read.xlsx('./ADaM-like/ADSL.xlsx')
MH <- read.xlsx("./SDTM/MH_MEDICALHISTORY.xlsx")
```

```{r adsl_prep}
ADSL_1 <- ADSL_1 %>% 
  select(STUDYID, USUBJID, TRTP, TRTPN) %>%
  mutate(TRTPN = as.integer(TRTPN))
```

# Предобработка MH
```{r mh_prep}
MH <- MH %>% 
  select(STUDYID, SUBJID, MHSEQ, MHCAT, MHTERM, MHDECOD, MHBODSYS, MHSTDTC, MHENDTC, MHENRTPT) %>%
  mutate(
    MHSEQ = as.integer(MHSEQ),
    USUBJID = paste(STUDYID, SUBJID, sep = "-"),
    MHENDTC = as.character(MHENDTC), 
    MHSTDTC = as.character(MHSTDTC)
  )
```


```{r}
colnames(MH_DATES)
```

```{r mh_dates}
MH_DATES <- MH %>% 
  group_by(USUBJID, STUDYID) %>% 
  mutate(
    N = length(MHSEQ[!is.na(MHSEQ)]),
    L = last(MHSEQ[!is.na(MHSEQ)])
  ) %>% 
  ungroup() %>% 
  mutate(TYPE = ifelse(MHSEQ == 1, 'ASTDT',
                       ifelse(MHSEQ == L, 'AENDT', '')),
         MHSTDTC = case_when(
           grepl("^\\d{4}-\\d{2}-\\d{2}$", MHSTDTC) ~ format(as.Date(MHSTDTC, format = "%Y-%m-%d"), "%d.%m.%Y"),
           grepl("^\\d{4}-\\d{2}$", MHSTDTC) ~ format(as.Date(paste0(MHSTDTC, "-01"), format = "%Y-%m-%d"), "%d.%m.%Y"),
           grepl("^\\d{4}$", MHSTDTC) ~ format(as.Date(paste0(MHSTDTC, "-01-01"), format = "%Y-%m-%d"), "%d.%m.%Y"),
           TRUE ~ NA_character_
         ),
         MHENDTC = case_when(
           grepl("^\\d{4}-\\d{2}-\\d{2}$", MHENDTC) ~ format(as.Date(MHENDTC, format = "%Y-%m-%d"), "%d.%m.%Y"),
           grepl("^\\d{4}-\\d{2}$", MHENDTC) ~ format(as.Date(paste0(MHENDTC, "-01"), format = "%Y-%m-%d"), "%d.%m.%Y"),
           grepl("^\\d{4}$", MHENDTC) ~ format(as.Date(paste0(MHENDTC, "-01-01"), format = "%Y-%m-%d"), "%d.%m.%Y"),
           TRUE ~ NA_character_
         )) %>% 
  filter(TYPE != '') %>% 
  select(STUDYID, USUBJID, MHSTDTC, MHENDTC, TYPE) %>% 
  spread(TYPE, MHSTDTC, fill = NA)
```

# Объединение ADSL и MH в ADMH
```{r admh_creation}
ADMH <- MH %>%
  left_join(ADSL_1, by = c("STUDYID", "USUBJID")) %>%
  left_join(MH_DATES %>% select(STUDYID, USUBJID, ASTDT, AENDT, MHENDTC), by = c("STUDYID", "USUBJID")) %>%
  mutate(
    ASTDT = as.Date(ASTDT, format = "%d.%m.%Y"),
    AENDT = as.Date(AENDT, format = "%d.%m.%Y"),
    ASTDTF = ifelse(is.na(ASTDT), "U", ""),
    AENDTF = ifelse(is.na(AENDT), "U", ""),
    MHENRF = ifelse(MHENRTPT == "ONGOING", "ONGOING", "")
  ) %>%
  select(STUDYID, USUBJID, TRTP, TRTPN, MHSEQ, MHCAT, MHTERM, MHDECOD, MHBODSYS, MHSTDTC, ASTDT, ASTDTF, MHENDTC.x, AENDT, AENDTF, MHENRTPT, MHENRF) %>%
  rename(MHENDTC = MHENDTC.x)
```

```{r}
# Согласно спецификации STUDYID, USUBJID, TRTP, TRTPN, MHSEQ, MHCAT, MHTERM, MHDECOD, MHBODSYS, MHSTDTC, ASTDT, ASTDTF, MHENDTC, AENDT, AENDTF, MHENRTPT, MHENRF
```

```{r}
str(ADMH)
```

```{r save_admh}
write.xlsx(ADMH, "ADMH.xlsx")
```